# Generated by Django 2.1.7 on 2019-04-01 11:07

import constrainedfilefield.fields.file
from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='BaseItems',
        ),
        migrations.AlterField(
            model_name='new',
            name='image',
            field=constrainedfilefield.fields.file.ConstrainedFileField(blank=True, content_types=['image/png', 'image/jpg'], max_upload_size=10240, mime_lookup_length=4096, null=True, upload_to='news'),
        ),
        migrations.AlterField(
            model_name='new',
            name='published_date',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
