# Generated by Django 2.1.7 on 2019-04-02 09:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0003_auto_20190402_0947'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank='True', default='/home/laranda/Proyecto_inicial/media/descarga.jpg', upload_to='news'),
        ),
    ]
