# Generated by Django 2.1.7 on 2019-04-02 09:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0006_auto_20190402_1113'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank='True', default='media/coche.jpeg', upload_to='news'),
        ),
    ]
