# Generated by Django 2.1.7 on 2019-04-02 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0007_auto_20190402_1146'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank='True', default='coche.jpeg', upload_to='news'),
        ),
    ]
