# Generated by Django 2.1.7 on 2019-04-02 10:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0010_auto_20190402_1230'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to='news'),
        ),
    ]
