# Generated by Django 2.1.7 on 2019-04-02 11:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0014_auto_20190402_1307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(upload_to=''),
        ),
    ]
