# Generated by Django 2.1.7 on 2019-04-05 09:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0016_auto_20190402_1335'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank='True', default='descarga.jpg', upload_to='news'),
        ),
    ]
