# Generated by Django 2.1.7 on 2019-04-05 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogNews', '0017_auto_20190405_1148'),
    ]

    operations = [
        migrations.AlterField(
            model_name='new',
            name='image',
            field=models.ImageField(blank='True', default='home/laranda/Proyecto_incial/descarga.jpg', upload_to='news'),
        ),
    ]
